version: "3.9"
services:
  pg:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: measurement-system
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./volumes/pg_data:/var/lib/comparing/data
    ports:
      - "5432:5432"

  measurement_gateway:
    build: ./measurement_gateway
    environment:
      DB_HOST: pg
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    volumes:
      - ./volumes/files:/measurement_gateway/files
    ports:
      - "8001:8000"

  admin_panel:
    build: ./admin_pannel
    environment:
      DATABASES__default__HOST: pg
    ports:
      - "8000:8000"

  file_processor:
    build: ./file_processor
    environment:
      DB_HOST: pg
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      FILE_DIR: files
    volumes:
      - ./volumes/files:/file_processor/files

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper-tests-infrastructure
    ports:
      - 2181:2181
    volumes:
      - ./volumes/zk-data:/var/lib/zookeeper/data
      - ./volumes/zk-txn-logs:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,PLAINTEXT://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,PLAINTEXT://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 100001200
    volumes:
      - ./volumes/kafka-data:/var/lib/kafka/data

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8090:8080
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
