"""Add tables

Revision ID: 0ac6d7cb4466
Revises: 
Create Date: 2022-06-04 17:11:47.190588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ac6d7cb4466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_description',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('gos_number', sa.String(), nullable=True),
    sa.Column('si_name', sa.String(), nullable=True),
    sa.Column('si_unit_of_measurement', sa.String(), nullable=True),
    sa.Column('si_measurement_error', sa.Float(), nullable=True),
    sa.Column('si_approval_date', sa.Date(), nullable=True),
    sa.Column('si_producer', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='measurement-data'
    )
    op.create_table('application_area',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('type_description_id', postgresql.UUID(), nullable=True),
    sa.Column('application_area_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['type_description_id'], ['measurement-data.type_description.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='measurement-data'
    )
    op.create_table('verification',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('type_description_id', postgresql.UUID(), nullable=True),
    sa.Column('si_modification', sa.String(), nullable=True),
    sa.Column('si_type', sa.String(), nullable=True),
    sa.Column('si_verification_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['type_description_id'], ['measurement-data.type_description.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='measurement-data'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification', schema='measurement-data')
    op.drop_table('application_area', schema='measurement-data')
    op.drop_table('type_description', schema='measurement-data')
    # ### end Alembic commands ###
