@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class "Область применения" {
   Имя области применения: varchar
   Id описание типа (внешний ключ): integer
}

class "Описание типа" {
   Id описание типа: integer
   Гос номер: varchar
   Имя СИ: varchar
   Единицы измерения СИ: varchar
   Ошибка измерения СИ: double precision
   Производитель СИ: varchar
   Дата утверждения СИ: date
   Имя файла: varchar
}

class Поверка {
   Id описание типа: integer
   Модификация СИ: varchar
   Тип СИ: varchar
   Дата поверки СИ: date
}

"Область применения"  -up[#595959,plain]-^  "Описание типа" : "Id описание типа:id"
Поверка      -up[#595959,plain]-^  "Описание типа" : "Id описание типа:id"
@enduml
