# Generated by Django 4.0.5 on 2022-06-04 19:56

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlembicVersion',
            fields=[
                ('version_num', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alembic_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('application_area_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Application area')),
            ],
            options={
                'verbose_name': 'Application area',
                'verbose_name_plural': 'Application areas',
                'db_table': 'measurement-data"."application_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('gos_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Government number')),
                ('si_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Name')),
                ('si_unit_of_measurement', models.CharField(blank=True, max_length=32, null=True, verbose_name='Measurement unit')),
                ('si_measurement_error', models.FloatField(blank=True, null=True, verbose_name='Measurement error')),
                ('si_approval_date', models.DateField(blank=True, null=True, verbose_name='Approval date')),
                ('si_producer', models.CharField(blank=True, max_length=32, null=True, verbose_name='Producer')),
                ('file_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='File name')),
            ],
            options={
                'verbose_name': 'Type description',
                'verbose_name_plural': 'Type descriptions',
                'db_table': 'measurement-data"."type_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('si_modification', models.CharField(blank=True, max_length=32, null=True, verbose_name='Modification')),
                ('si_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='Type')),
                ('si_verification_date', models.DateField(blank=True, null=True, verbose_name='Verification date')),
            ],
            options={
                'verbose_name': 'Verification',
                'verbose_name_plural': 'Verifications',
                'db_table': 'measurement-data"."verification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegexSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_description', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None, verbose_name='Type description')),
                ('meaning', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None, verbose_name='SI meaning')),
                ('measurement_unit', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None, verbose_name='Measurement units')),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None, verbose_name='SI description')),
            ],
            options={
                'db_table': 'measurement-admin"."regex_settings',
            },
        ),
    ]
