# Generated by Django 4.0.5 on 2022-06-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlembicVersion',
            fields=[
                ('version_num', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alembic_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationArea',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('application_area_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'application_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeDescription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gos_number', models.CharField(blank=True, max_length=32, null=True)),
                ('si_name', models.CharField(blank=True, max_length=32, null=True)),
                ('si_unit_of_measurement', models.CharField(blank=True, max_length=32, null=True)),
                ('si_measurement_error', models.FloatField(blank=True, null=True)),
                ('si_approval_date', models.DateField(blank=True, null=True)),
                ('si_producer', models.CharField(blank=True, max_length=32, null=True)),
                ('file_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'type_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('si_modification', models.CharField(blank=True, max_length=32, null=True)),
                ('si_type', models.CharField(blank=True, max_length=32, null=True)),
                ('si_verification_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'verification',
                'managed': False,
            },
        ),
    ]
