# Generated by Django 4.0.5 on 2022-06-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationarea',
            options={'managed': False, 'verbose_name': 'Application area', 'verbose_name_plural': 'Application areas'},
        ),
        migrations.AlterModelOptions(
            name='typedescription',
            options={'managed': False, 'verbose_name': 'Type description', 'verbose_name_plural': 'Type descriptions'},
        ),
        migrations.AlterModelOptions(
            name='verification',
            options={'managed': False, 'verbose_name': 'Verification', 'verbose_name_plural': 'Verifications'},
        ),
    ]
